# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : publish release to github
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

name: "📦 Publish"
run-name: "📦 Publish"

# ---------------------------------------------------------------------------------------
#   triggers
# ---------------------------------------------------------------------------------------

on:
  workflow_dispatch:
    inputs:

      # ---------------------------------------------------------------------------------------
      #   Name of the plugin to use when creating the release zip filename
      #     e.g: mobapy-v1.0.0.zip
      # ---------------------------------------------------------------------------------------

      PLUGIN_NAME:
        description:  "📦 Name of Plugin"
        required:     true
        default:      'mobapy'
        type:         string

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   the changelog generated in releases tab will only display single commits.
      #   DISABLE:  the changelog shows pull requests completed based on their labels
      # ---------------------------------------------------------------------------------------

      CHANGELOG_MODE_COMMIT:
        description:  "📑 Use Commits Instead of PRs"
        required:     true
        default:      true
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   Will show all types of commits, including uncategorized
      #   DISABLE:  WIll only show actions that have been categorized using the format
      #                type(scope): description
      #                type: description
      # ---------------------------------------------------------------------------------------

      SHOW_UNCATEGORIZED:
        description:  "🗂️ Show Uncategorized Commits"
        required:     true
        default:      false
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   released version will be marked as pre-release
      #   DISABLE:  release version will be marked as stable / normal release
      # ---------------------------------------------------------------------------------------

      PRERELEASE:
        description:  "🧪 Build RC (Pre-release)"
        required:     true
        default:      false
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   Release Candidate version number
      #   this will be added to the end of your released app in the releases page.
      #     e.g: mobapy-v1.0.0-rc.1
      # ---------------------------------------------------------------------------------------

      VERSION_RC:
        description:  "🧪 RC (Pre-release) Ver (mobapy-rc.v1)"
        required:     false
        type:         string
        default:      "1"

# ---------------------------------------------------------------------------------------
#   jobs
# ---------------------------------------------------------------------------------------

jobs:

    # ---------------------------------------------------------------------------------------
    #   JOB > INITIALIZE
    # ---------------------------------------------------------------------------------------

    job-initialize:
        name: >-
          📦 Publish › Initialize
        runs-on: ubuntu-latest
        outputs:
          package_version: ${{ steps.task_initialize_package_version.outputs.PACKAGE_VERSION }}
        permissions:
            contents: write
            packages: write
        steps:

            # ---------------------------------------------------------------------------------------
            #   Job > Initialize > Start
            # ---------------------------------------------------------------------------------------

            - name: "✅ Start"
              id: task_initialize_start
              run: |
                    echo "Starting build"

            # ---------------------------------------------------------------------------------------
            #   Job > Initialize > Checkout
            # ---------------------------------------------------------------------------------------

            - name: "☑️ Checkout"
              id: task_initialize_checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            # ---------------------------------------------------------------------------------------
            #   Package Version > Set
            #   Get version from package.json VERSION value
            # ---------------------------------------------------------------------------------------

            - name: "👁️‍🗨️ Package Version › Get"
              id: task_initialize_package_version
              run: |
                VER=$(cat package.json | jq -r '.version')
                echo "PACKAGE_VERSION=$VER" >> $GITHUB_OUTPUT

            # ---------------------------------------------------------------------------------------
            #   Package Version > Print (Debug)
            # ---------------------------------------------------------------------------------------

            - name: "👁️‍🗨️ Package Version › Print"
              id: task_initialize_package_version_print
              run: |
                echo "VERSION: ${{ steps.task_initialize_package_version.outputs.PACKAGE_VERSION }}"

    # ---------------------------------------------------------------------------------------
    #   Job > NPM
    # ---------------------------------------------------------------------------------------

    job-npm:
        name: >-
          📦 NPM
        runs-on: ubuntu-latest
        needs: [ job-initialize ]
        env:
          PACKAGE_VERSION: ${{ needs.job-initialize.outputs.package_version }}
        permissions:
            contents: write
            packages: write
        steps:

            # ---------------------------------------------------------------------------------------
            #   Dist Releases > Checkout
            # ---------------------------------------------------------------------------------------

            - name: "☑️ Checkout"
              id: task_release_checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            # ---------------------------------------------------------------------------------------
            #   Debug : View passed values
            # ---------------------------------------------------------------------------------------

            - name: "⚙️ Debug › Passed Values"
              id: task_npm_debug_print_vals_1
              run: |
                echo "VERSION ............. ${{ env.PACKAGE_VERSION }}"

            # ---------------------------------------------------------------------------------------
            #   Dist Releases > Install package via NPM
            # ---------------------------------------------------------------------------------------

            - name: "🪪 Install Dependencies"
              id: task_release_npm_install
              run: |
                npm install

            # ---------------------------------------------------------------------------------------
            #   Dist Releases > Execute npm generate so that a uuid and guid can be created
            # ---------------------------------------------------------------------------------------

            - name: "🪪 Generate IDs"
              id: task_release_npm_env_generate
              run: |
                npm run release:generate

    # ---------------------------------------------------------------------------------------
    #   JOBS > BUILD
    # ---------------------------------------------------------------------------------------

    # job-build
    build:
        name: >-
          🔨 Build Exe
        runs-on: ubuntu-latest
        needs: [ job-initialize, job-npm ]
        env:
          PACKAGE_VERSION: ${{ needs.job-initialize.outputs.package_version }}
        outputs:
          package_filename: ${{ steps.build_handle_tarball.outputs.PACKAGE_FILENAME }}
        steps:
            - name: "✅ Start"
              run: |
                    echo "Starting build"

            # ---------------------------------------------------------------------------------------
            #   Job > Build > Checkout
            # ---------------------------------------------------------------------------------------

            - name: "☑️ Checkout"
              id: task_build_checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            # ---------------------------------------------------------------------------------------
            #   Debug > View passed values
            # ---------------------------------------------------------------------------------------

            - name: "⚙️ Debug › Passed Values"
              id: task_build_debug_print_vals_1
              run: |
                echo "VERSION ............. ${{ env.PACKAGE_VERSION }}"

            # ---------------------------------------------------------------------------------------
            #   Python > Install
            #
            #   development station used v3.12.4
            # ---------------------------------------------------------------------------------------

            - name: "🐍 Python › Setup"
              id: task_build_python_setup
              uses: actions/setup-python@v5
              with:
                python-version: '3.9'

            # ---------------------------------------------------------------------------------------
            #   Python > Dependencies
            #
            #   development station used v6.3.0
            # ---------------------------------------------------------------------------------------

            - name: "🐍 Python › Build Tools"
              id: task_build_python_tools
              # PyInstaller >=6.0 results in significantly more antivirus false positives
              run: |
                python -m pip install --upgrade pip
                pip install pyinstaller==5.3.0

            # ---------------------------------------------------------------------------------------
            #   build python script
            #
            #   creates folder 'build'
            #   temp files placed in 'tnp'
            #   will compile files from 'src' folder
            # ---------------------------------------------------------------------------------------

            - name: "🐍 Python › Build"
              id: build_handle_tarball
              run: |
                echo "Starting build: Mobaxterm Utility"
                mkdir build tmp

                pyinstaller -Fwc "src/mobaxtgen_cli.py" --version-file="src/verinfo.py" -i "src/moba.ico" --distpath "build" --workpath "tmp"

                PACKAGE=$(find output/*.exe -type f -printf "%f\n")
                echo "PACKAGE_FILENAME=build/$PACKAGE" >> $GITHUB_OUTPUT

            # ---------------------------------------------------------------------------------------
            #   Debug : View passed values
            # ---------------------------------------------------------------------------------------

            - name: "⚙️ Debug › Passed Values"
              id: task_build_debug_print_vals_2
              run: |
                echo "VERSION ............. ${{ env.PACKAGE_VERSION }}"
                echo "PACKAGE FILENAME .... ${{ steps.build_handle_tarball.outputs.PACKAGE_FILENAME }}"
